lsi: false
safe: true
source: [/doc]
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
# Enable collections for slides
collections:
  slides:
    output: true
# Site title
title: "Reveal.js Slide Decks"
baseurl: "" # Make sure this is set correctly
